Repository LikeLion-12th-SKHU/LikeLion-12th-TEAM02-BE, pull requests merged in 2024-07, with the labels that each got.

#3 ✨ Feat: 데이터베이스 설계 (#2)
  src/main/java/com/skhu/moodfriend/app/entity/diary/Diary.java
  src/main/java/com/skhu/moodfriend/app/entity/diary_ai/DiaryAI.java
  src/main/java/com/skhu/moodfriend/app/entity/emotion_tracker/EmotionTracker.java
  src/main/java/com/skhu/moodfriend/app/entity/feedback/FeedBack.java
  src/main/java/com/skhu/moodfriend/app/entity/friend/Friend.java
  src/main/java/com/skhu/moodfriend/app/entity/friend/Status.java
  src/main/java/com/skhu/moodfriend/app/entity/object_store/ObjectStore.java
  src/main/java/com/skhu/moodfriend/app/entity/user/EmotionType.java
  src/main/java/com/skhu/moodfriend/app/entity/user/LoginType.java
  src/main/java/com/skhu/moodfriend/app/entity/user/User.java
  src/main/java/com/skhu/moodfriend/app/entity/user_object/UserObject.java
Labels: ✨ Feat, ⚙️ Setting

#4 ✨Feat: 데이터베이스 수정 (#2)
  src/main/java/com/skhu/moodfriend/app/entity/attendance/Attendance.java
  src/main/java/com/skhu/moodfriend/app/entity/user/User.java
Labels: ✨ Feat

#5 💚 Fix: Health Check 시간 연장 (#1)
  scripts/health.sh
Labels: 🌎 Deploy, ⚒️ Fix

#6 💚 Fix: cors 주석 처리 (#1)
  scripts/health.sh
  src/main/java/com/skhu/moodfriend/global/config/SecurityConfig.java
Labels: 🌎 Deploy, ⚒️ Fix

#7 💚 Fix: /profile 경로 접근 (#1)
  src/main/java/com/skhu/moodfriend/app/controller/ProfileController.java
  src/main/java/com/skhu/moodfriend/global/config/SecurityConfig.java
Labels: 🌎 Deploy, ⚒️ Fix

#8 💚 Fix: CI/CD 오류 해결
  src/main/java/com/skhu/moodfriend/app/controller/ProfileController.java
  src/main/java/com/skhu/moodfriend/global/config/SecurityConfig.java
Labels: 🌎 Deploy, ⚒️ Fix

#13 ✨ Feat: 사용자 정보 구현
  src/main/java/com/skhu/moodfriend/app/controller/member/MemberInfoController.java
  src/main/java/com/skhu/moodfriend/app/dto/member/reqDto/MemberInfoUpdateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/member/resDto/MemberInfoResDto.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/service/member/MemberInfoService.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
Labels: ✨ Feat

#18 Feat: 구글 로그인 구현
  src/main/java/com/skhu/moodfriend/app/controller/auth/AuthController.java
  src/main/java/com/skhu/moodfriend/app/controller/auth/OAuthController.java
  src/main/java/com/skhu/moodfriend/app/dto/auth/resDto/OAuthResDto.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/service/auth/GoogleOAuthService.java
  src/main/java/com/skhu/moodfriend/global/dto/MemberInfo.java
  src/main/java/com/skhu/moodfriend/global/dto/Token.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
  src/main/resources/application.yml
Labels: ✨ Feat

#19 Rename: OAuthController 로직 이동
  src/main/java/com/skhu/moodfriend/app/controller/auth/AuthController.java
  src/main/java/com/skhu/moodfriend/app/controller/auth/OAuthController.java
  src/main/java/com/skhu/moodfriend/app/service/auth/GoogleOAuthService.java
Labels: ♻️ Refactor

#20 Feat: 일기 CRUD 구현
  src/main/java/com/skhu/moodfriend/MoodfriendApplication.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryDisplayController.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/DiaryCreateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/DiaryUpdateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/DiaryResDto.java
  src/main/java/com/skhu/moodfriend/app/entity/diary/Diary.java
  src/main/java/com/skhu/moodfriend/app/entity/diary/EmotionType.java
  src/main/java/com/skhu/moodfriend/app/entity/diary/WeatherType.java
  src/main/java/com/skhu/moodfriend/app/entity/diary_ai/DiaryAI.java
  src/main/java/com/skhu/moodfriend/app/entity/emotion_tracker/EmotionTracker.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/entity/tracker/Tracker.java
  src/main/java/com/skhu/moodfriend/app/repository/DiaryRepository.java
  src/main/java/com/skhu/moodfriend/app/repository/TrackerRepository.java
  src/main/java/com/skhu/moodfriend/app/service/auth/GoogleOAuthService.java
  src/main/java/com/skhu/moodfriend/app/service/auth/SignUpService.java
  src/main/java/com/skhu/moodfriend/app/service/member/MemberInfoService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryCreateService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryModifyService.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ Feat, ⚒️ Fix

#21 Refactor: 유효성 검사 리팩토링
  build.gradle
  src/main/java/com/skhu/moodfriend/app/controller/auth/AuthController.java
  src/main/java/com/skhu/moodfriend/app/controller/member/MemberInfoController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryController.java
  src/main/java/com/skhu/moodfriend/app/dto/auth/reqDto/SignUpReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/member/reqDto/MemberInfoUpdateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/DiaryCreateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/DiaryUpdateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/DiaryResDto.java
  src/main/java/com/skhu/moodfriend/app/entity/diary/Diary.java
  src/main/java/com/skhu/moodfriend/app/entity/diary/EmotionType.java
  src/main/java/com/skhu/moodfriend/app/entity/diary/WeatherType.java
  src/main/java/com/skhu/moodfriend/app/service/auth/LoginService.java
  src/main/java/com/skhu/moodfriend/app/service/auth/SignUpService.java
  src/main/java/com/skhu/moodfriend/app/service/member/MemberInfoService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryCreateService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryModifyService.java
  src/main/java/com/skhu/moodfriend/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/skhu/moodfriend/global/exception/CustomException.java
  src/main/java/com/skhu/moodfriend/global/exception/EnumValid.java
  src/main/java/com/skhu/moodfriend/global/exception/EnumValidator.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
Labels: ♻️ Refactor

#26 Feat: 일일 출석 구현
  src/main/java/com/skhu/moodfriend/app/controller/member/AttendanceController.java
  src/main/java/com/skhu/moodfriend/app/entity/attendance/Attendance.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/repository/AttendanceRepository.java
  src/main/java/com/skhu/moodfriend/app/service/auth/GoogleOAuthService.java
  src/main/java/com/skhu/moodfriend/app/service/auth/KakaoOAuthService.java
  src/main/java/com/skhu/moodfriend/app/service/member/AttendanceService.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
Labels: ✨ Feat

#27 Feat: 월별 감정 조회 구현
  src/main/java/com/skhu/moodfriend/app/controller/tracker/EmotionDisplayController.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/MonthlyEmotionReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/MonthlyEmotionResDto.java
  src/main/java/com/skhu/moodfriend/app/repository/DiaryRepository.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryCreateService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryModifyService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/EmotionDisplayService.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
Labels: ✨ Feat

#29 Feat: 사용자 주변 의료기관 추천
  build.gradle
  src/main/java/com/skhu/moodfriend/MoodfriendApplication.java
  src/main/java/com/skhu/moodfriend/app/controller/hospital/HospitalController.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/KakaoMapDocument.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/KakaoMapKeyword.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/reqDto/KakaoMapKeywordReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/resDto/KakaoMapKeywordResDto.java
  src/main/java/com/skhu/moodfriend/app/repository/KakaoMapRepository.java
  src/main/java/com/skhu/moodfriend/app/service/hospital/HospitalService.java
  src/main/java/com/skhu/moodfriend/app/service/hospital/KakaoMapService.java
  src/main/resources/application.yml
Labels: ✨ Feat

#31 Fix: 사용자 주변 의료기관 추천
  src/main/java/com/skhu/moodfriend/MoodfriendApplication.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/HospitalDisplayController.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/KakaoMapDocument.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/KakaoMapKeyword.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/reqDto/KakaoMapKeywordReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/hospital/resDto/KakaoMapKeywordResDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/HospitalReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/HospitalResDto.java
  src/main/java/com/skhu/moodfriend/app/repository/KakaoMapRepository.java
  src/main/java/com/skhu/moodfriend/app/service/hospital/HospitalService.java
  src/main/java/com/skhu/moodfriend/app/service/hospital/KakaoMapService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/HospitalDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/KakaoMapService.java
  src/main/java/com/skhu/moodfriend/global/config/FeignConfig.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
Labels: ⚒️ Fix, ♻️ Refactor

#32 Feat: 호야 챗봇 구현
  src/main/java/com/skhu/moodfriend/app/controller/chat/HoyaController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/EmotionDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/HospitalDisplayController.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/Message.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/reqDto/HoyaReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/resDto/HoyaResDto.java
  src/main/java/com/skhu/moodfriend/app/service/chat/HoyaService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryCreateService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryModifyService.java
  src/main/java/com/skhu/moodfriend/global/config/OpenAIConfig.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
  src/main/resources/application.yml
Labels: ✨ Feat

#34 Fix: 사용자 일기 수정
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/DiaryResDto.java
  src/main/java/com/skhu/moodfriend/app/service/chat/HoyaService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryCreateService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryModifyService.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
Labels: ⚒️ Fix

#36 Feat: 호야 챗봇 초기 구현
  src/main/java/com/skhu/moodfriend/app/controller/chat/HoyaController.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/Translation.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/reqDto/HoyaReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/reqDto/TranslationReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/resDto/HoyaResDto.java
  src/main/java/com/skhu/moodfriend/app/dto/chat/resDto/TranslationResDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/DiaryCreateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/reqDto/DiaryUpdateReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/DiaryResDto.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/MonthlyEmotionResDto.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/entity/member/attendance/Attendance.java
  src/main/java/com/skhu/moodfriend/app/entity/member/feedback/FeedBack.java
  src/main/java/com/skhu/moodfriend/app/entity/member/member_object/MemberObject.java
  src/main/java/com/skhu/moodfriend/app/entity/object_store/ObjectStore.java
  src/main/java/com/skhu/moodfriend/app/entity/tracker/Tracker.java
  src/main/java/com/skhu/moodfriend/app/entity/tracker/diary/Diary.java
  src/main/java/com/skhu/moodfriend/app/entity/tracker/diary/EmotionType.java
  src/main/java/com/skhu/moodfriend/app/entity/tracker/diary/WeatherType.java
  src/main/java/com/skhu/moodfriend/app/entity/tracker/diary_ai/DiaryAI.java
  src/main/java/com/skhu/moodfriend/app/repository/AttendanceRepository.java
  src/main/java/com/skhu/moodfriend/app/repository/DiaryAIRepository.java
  src/main/java/com/skhu/moodfriend/app/repository/DiaryRepository.java
  src/main/java/com/skhu/moodfriend/app/repository/TrackerRepository.java
  src/main/java/com/skhu/moodfriend/app/service/chat/ConversationCleanupService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/ConversationService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/ConversationSummaryService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/HoyaService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/TranslationService.java
  src/main/java/com/skhu/moodfriend/app/service/member/AttendanceService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryCreateService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryModifyService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/EmotionDisplayService.java
  src/main/java/com/skhu/moodfriend/global/config/SchedulingConfig.java
  src/main/java/com/skhu/moodfriend/global/exception/ControllerExceptionAdvice.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ Feat

#38 Feat: AI 일기 조회, 삭제 구현
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryAIController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryAIDisplayController.java
  src/main/java/com/skhu/moodfriend/app/dto/tracker/resDto/DiaryAIResDto.java
  src/main/java/com/skhu/moodfriend/app/repository/DiaryAIRepository.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryAIDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/tracker/DiaryAIModifyService.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
Labels: ✨ Feat

#41 Feat: 결제 서비스 구현
  build.gradle
  src/main/java/com/skhu/moodfriend/app/controller/payment/OrderDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/payment/PaymentController.java
  src/main/java/com/skhu/moodfriend/app/dto/order/reqDto/OrderReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/order/resDto/OrderResDto.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/entity/member/object/MemberObject.java
  src/main/java/com/skhu/moodfriend/app/entity/member/order/Order.java
  src/main/java/com/skhu/moodfriend/app/entity/object_store/ObjectName.java
  src/main/java/com/skhu/moodfriend/app/entity/object_store/ObjectStore.java
  src/main/java/com/skhu/moodfriend/app/repository/MemberObjectRepository.java
  src/main/java/com/skhu/moodfriend/app/repository/OrderRepository.java
  src/main/java/com/skhu/moodfriend/app/service/member/AttendanceService.java
  src/main/java/com/skhu/moodfriend/app/service/payment/OrderDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/payment/PaymentService.java
  src/main/java/com/skhu/moodfriend/global/config/PortOneConfig.java
  src/main/java/com/skhu/moodfriend/global/config/SecurityConfig.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: ✨ Feat

#42 Refactor: 스웨거 문서 및 패키지 구조 변경
  src/main/java/com/skhu/moodfriend/app/controller/ProfileController.java
  src/main/java/com/skhu/moodfriend/app/controller/chat/HoyaController.java
  src/main/java/com/skhu/moodfriend/app/controller/member/AttendanceController.java
  src/main/java/com/skhu/moodfriend/app/controller/member/MemberController.java
  src/main/java/com/skhu/moodfriend/app/controller/member/MemberInfoController.java
  src/main/java/com/skhu/moodfriend/app/controller/payment/OrderDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/payment/PaymentController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryAIController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryAIDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/DiaryDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/EmotionDisplayController.java
  src/main/java/com/skhu/moodfriend/app/controller/tracker/HospitalDisplayController.java
  src/main/java/com/skhu/moodfriend/app/dto/member/reqDto/HospitalReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/member/reqDto/MonthlyEmotionReqDto.java
  src/main/java/com/skhu/moodfriend/app/dto/member/resDto/HospitalResDto.java
  src/main/java/com/skhu/moodfriend/app/dto/member/resDto/MonthlyEmotionResDto.java
  src/main/java/com/skhu/moodfriend/app/service/member/EmotionDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/member/HospitalDisplayService.java
  src/main/java/com/skhu/moodfriend/app/service/member/KakaoMapService.java
  src/main/resources/application.yml
Labels: ♻️ Refactor

#43 Feat: 친구 추가, 삭제, 리스트 조회 구현
  src/main/java/com/skhu/moodfriend/app/controller/friend/FriendController.java
  src/main/java/com/skhu/moodfriend/app/dto/friend/reqDto/FriendRequestDto.java
  src/main/java/com/skhu/moodfriend/app/dto/friend/resDto/FriendListDto.java
  src/main/java/com/skhu/moodfriend/app/entity/friend/Friend.java
  src/main/java/com/skhu/moodfriend/app/entity/member/Member.java
  src/main/java/com/skhu/moodfriend/app/entity/member/object/MemberObject.java
  src/main/java/com/skhu/moodfriend/app/repository/FriendRepository.java
  src/main/java/com/skhu/moodfriend/app/service/friend/FriendService.java
  src/main/java/com/skhu/moodfriend/global/dto/PagedResponse.java
  src/main/java/com/skhu/moodfriend/global/exception/code/ErrorCode.java
  src/main/java/com/skhu/moodfriend/global/exception/code/SuccessCode.java
  src/main/java/com/skhu/moodfriend/global/template/ApiResponseTemplate.java
  src/main/resources/application.yml
Labels: ✨ Feat

#47 Feat: 프롬프트 엔지니어링 추가
  src/main/java/com/skhu/moodfriend/app/controller/friend/FriendController.java
  src/main/java/com/skhu/moodfriend/app/repository/DiaryAIRepository.java
  src/main/java/com/skhu/moodfriend/app/service/auth/GoogleOAuthService.java
  src/main/java/com/skhu/moodfriend/app/service/auth/KakaoOAuthService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/ConversationCleanupService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/ConversationService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/ConversationSummaryService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/HoyaService.java
  src/main/java/com/skhu/moodfriend/app/service/chat/TranslationService.java
  src/main/resources/application.yml
Labels: ✨ Feat
